services:
  - type: web
    name: nexbid-web
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexbid-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: nexbid-redis
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_FROM
        value: noreply@nexbid.com
      - key: RESEND_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false

  - type: keyvalue
    name: nexbid-redis
    plan: free
    ipAllowList: [] # internally restricted to services in the same blueprint

databases:
  - name: nexbid-db
    databaseName: nexbid_db
    user: nexbid_user
    plan: free
